name: Release

on:
    push:
        branches:
            - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
            id-token: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
              with:
                  fetch-depth: 0

            - name: Set up Node.js
              uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
              with:
                  node-version: 24.18.0
                  package-manager-cache: false

            - name: Enable Corepack
              run: corepack enable

            - name: Fetch base branch
              run: git fetch origin +main:main

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Verify
              run: pnpm verify

            - name: Create release pull request or publish to npm
              id: changesets
              uses: changesets/action@3841a0683d3cfa6dae0f9bb335290003010fe3f0 # v1.9.0
              with:
                  publish: pnpm release
